### ISSUE TITLE
Breaks when symbol doesn't exist

### ISSUE THREAD

**Issue by Stono** [pilwon/node-google-finance#6]
[ 'LON:VM', 'LON:BARC', 'LON:IDONTEXIST' ]

Unhandled rejection StatusCodeError: 400 - "<!DOCTYPE html><html lang=en><meta charset=utf-8><meta name=viewport content=\"initial-scale=1, minimum-scale=1, width=device-width\"><title>Error 400 (Not Found)!!1</title><style>_{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px;}_ > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}pre{white-space:pre-wrap;}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}</style><div id=\"af-error-container\"><a href=//www.google.com/><span id=logo aria-label=Google></span></a><p><b>400.</b> <ins>That’s an error.</ins><p>The requested URL was not found on this server. <ins>That’s all we know.</ins></div>"
    at new StatusCodeError (/Users/kstoney/Development/stono/stocknet/sn.crawl.news/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/Users/kstoney/Development/stono/stocknet/sn.crawl.news/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback](/Users/kstoney/Development/stono/stocknet/sn.crawl.news/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/Users/kstoney/Development/stono/stocknet/sn.crawl.news/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/kstoney/Development/stono/stocknet/sn.crawl.news/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/kstoney/Development/stono/stocknet/sn.crawl.news/node_modules/request/request.js:965:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:934:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by thstarshine** [comment]
Use request instead of request-promise at line 29 in lib/utils.js temprorarily solved this.
btw pipe streaming is discouraged when using [request-promise](https://github.com/request/request-promise), maybe the **downloadRSS** function could be written in another way?

>
    var requestCb = require('request')

>
    var req = requestCb(_.extend({
      uri: uri,
      qs: qs
    }, optionalHttpRequestOptions));
